#!/bin/bash

## -----------------------------------------------------------------------------------------
## Truncate a couple of common commands that are used herein
## -----------------------------------------------------------------------------------------

_bc() {
    bspc config "$@"
}

_br() {
     bspc rule --add "$@"
}


## -----------------------------------------------------------------------------------------
## Workspaces Names
## -----------------------------------------------------------------------------------------

bspc monitor -d CHAT TERM WEB CODE OTHER

## -----------------------------------------------------------------------------------------
## #### Desktop Layouts (tiled is the default) 
##------------------------------------------------------------------------------------------

bspc desktop CHAT -l monocle
bspc desktop WEB  -l monocle

## -----------------------------------------------------------------------------------------
## bspwm config
## -----------------------------------------------------------------------------------------
_bc top_padding           44
_bc window_gap            4
_bc border_width          2
_bc split_ratio           0.50
_bc left_padding          0
_bc right_padding         0
_bc borderless_monocle    true
_bc gapless_monocle       true
_bc focus_by_distance     true
_bc focus_follows_pointer true
_bc pointer_follows_focus false
_bc honor_size_hints      true

##------------------------------------------------------------------------------------------
## Border Colors
##------------------------------------------------------------------------------------------

_bc focused_border_color                "#EEEEEF"
_bc active_border_color                 "#5C5955"
_bc normal_border_color                 "#34322E"
_bc presel_border_color                 "#F6F9FF"
_bc focused_locked_border_color         "#CFB776"
_bc active_locked_border_color          "#5C5955"
_bc normal_locked_border_color          "#34322E"
_bc focused_sticky_border_color         "#E3A5DA"
_bc active_sticky_border_color          "#5C5955"
_bc normal_sticky_border_color          "#34322E"
_bc focused_private_border_color        "#42CAD9"
_bc config active_private_border_color  "#5C5955"
_bc config normal_private_border_color  "#34322E"
_bc config urgent_border_color          "#F9A299"

## ----------------------------------------------------------------------------------------
## Rules
## ----------------------------------------------------------------------------------------

_br 'Pale moon'  desktop=^3 follow=on border=off
_br Telegram     desktop=^1 follow=on border=off focus=on
_br Mpv follow=off state=floating

##------------------------------------------------------------------------------------------
## Autostart programs + scripts
##------------------------------------------------------------------------------------------

2bspwm &

##Polybar: top bar
"$HOME"/.config/polybar/launch.sh
